<?php
require_once '../../database.php'; 
include '../header.php';

// Query all facilities to populate the dropdown menu
$facilities_query = $conn->query('SELECT FacilityID, Name FROM Facilities ORDER BY Name');
$facilities = $facilities_query->fetch_all(MYSQLI_ASSOC);

// Check if the user has submitted a form
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get the selected facility ID from the form data
    $facility_id = $_POST['facility_id'];
    
    // Query the emails generated by the selected facility, ordered by date
    $statement = $conn->prepare('SELECT e.Email, el.Date, el.Subject, el.Body
        FROM EmailLog el
        INNER JOIN Employees e ON el.EmployeeID = e.EmployeeID
        WHERE el.FacilityID = ?
        ORDER BY el.Date ASC');
    $statement->bind_param('i', $facility_id);
    $statement->execute();
    $results = $statement->get_result()->fetch_all(MYSQLI_ASSOC);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../pages/style.css">
    <title>Query 10</title>
</head>
<body>
    <h1>Emails by facility</h1>
    <form method="post">
        <label for="facility_id">Select a facility:</label>
        <select id="facility_id" name="facility_id">
            <?php foreach ($facilities as $facility) { ?>
                <option value="<?php echo $facility['FacilityID']; ?>"><?php echo $facility['Name']; ?></option>
            <?php } ?>
        </select>
        <button type="submit">View Emails</button>
    </form>

    <?php if (isset($results)) { ?>
        <table>
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Subject</th>
                    <th>Body</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results as $row) { ?>
                    <tr>
                        <td><?php echo $row['Email']; ?></td>
                        <td><?php echo $row['Date']; ?></td>
                        <td><?php echo $row['Subject']; ?></td>
                        <td><?php echo $row['Body']; ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php } ?>

    <a href="../../index.php">Back to main page</a>
</body>
</html>
